### ISSUE TITLE
Dynamic Transforms

### ISSUE THREAD

**Issue by DeVoresyah** [OsmiCSX/osmicsx#30]
# Table of Contents
- [x] [Translate](#translate) - Added in PR #33 by @deyusf 
- [X] [Scale](#scale) - Added in PR #35 by @DeVoresyah 
- [x] [Rotate](#rotate) - Added in PR #36 by @DeVoresyah 
- [x] [Skew](#skew) - Added in PR #34 by @deyusf 

---

So for now, OsmiCSX doesn't support yet for dynamic transform. Like you want to use Translate X/Y with dynamic value or Rotate and Skew. By adding support for a dynamic transform will make OsmiCSX compatible with `useAnimatedStyle()` from Reanimated v2.

## Translate
Translate must be support for positive numbers and negative numbers. List of expected syntax:
- `translate-x-{amount}`
- `translate-y-{amount}`
- `-translate-x-{amount}`
- `-translate-y-{amount}`

### Example Input
```jsx
apply("translate-x-50")
```
```jsx
apply("translate-y-50")
```
```jsx
apply("-translate-x-100")
```
```jsx
apply("-translate-y-100")
```

### Example Output
```jsx
{
  transform: [{ translateX: 50 }]
}
```
```jsx
{
  transform: [{ translateY: 50 }]
}
```
```jsx
{
  transform: [{ translateX: -100 }]
}
```
```jsx
{
  transform: [{ translateY: -100 }]
}
```

## Scale
Scale must be support for positive numbers and negative numbers. List of expected syntax:
- `scale-{amount}`
- `-scale-{amount}`
- `scale-x-{amount}`
- `scale-y-{amount}`
- `-scale-x-{amount}`
- `-scale-y-{amount}`

### Example Input
```jsx
apply("scale-25")
```
```jsx
apply("-scale-25")
```
```jsx
apply("scale-x-50")
```
```jsx
apply("scale-y-50")
```
```jsx
apply("-scale-x-100")
```
```jsx
apply("-scale-y-100")
```

### Example Output
```jsx
{
  transform: [{ scale: 25 }]
}
```
```jsx
{
  transform: [{ scale: -25 }]
}
```
```jsx
{
  transform: [{ scaleX: 50 }]
}
```
```jsx
{
  transform: [{ scaleY: 50 }]
}
```
```jsx
{
  transform: [{ scaleX: -100 }]
}
```
```jsx
{
  transform: [{ scaleY: -100 }]
}
```

## Rotate
Rotate must be support for positive numbers and negative numbers. And also should support for `degrees (deg)` and `radians (rad)`. List of expected syntax:
- `rotate-{amount}`
- `-rotate-{amount}`
- `rotate-x-{amount}`
- `rotate-y-{amount}`
- `rotate-z-{amount}`
- `-rotate-x-{amount}`
- `-rotate-y-{amount}`
- `-rotate-z-{amount}`

### Example Input
```jsx
apply("rotate-25")
```
```jsx
apply("-rotate-25")
```
```jsx
apply("rotate-x-50")
```
```jsx
apply("rotate-y-50")
```
```jsx
apply("rotate-z-50")
```
```jsx
apply("-rotate-x-100")
```
```jsx
apply("-rotate-y-100")
```
```jsx
apply("-rotate-z-100")
```

### Example Output
Somehow the output can be expressed in `degrees (deg)` or `radians (rad)`
```jsx
{
  transform: [{ rotate: "25" }]
}
```
```jsx
{
  transform: [{ rotate: "-25" }]
}
```
```jsx
{
  transform: [{ rotateX: "50" }]
}
```
```jsx
{
  transform: [{ rotateY: "50" }]
}
```
```jsx
{
  transform: [{ rotateZ: "50" }]
}
```
```jsx
{
  transform: [{ rotateX: "-100" }]
}
```
```jsx
{
  transform: [{ rotateY: "-100" }]
}
```
```jsx
{
  transform: [{ rotateZ: "-100" }]
}
```

## Skew
Skew must be support for positive numbers and negative numbers. List of expected syntax:
- `skew-x-{amount}`
- `skew-y-{amount}`
- `-skew-x-{amount}`
- `-skew-y-{amount}`

### Example Input
```jsx
apply("skew-x-50")
```
```jsx
apply("skew-y-50")
```
```jsx
apply("-skew-x-100")
```
```jsx
apply("-skew-y-100")
```

### Example Output
```jsx
{
  transform: [{ skewX: "50deg" }]
}
```
```jsx
{
  transform: [{ skewY: "50deg" }]
}
```
```jsx
{
  transform: [{ skewX: "-100deg" }]
}
```
```jsx
{
  transform: [{ skewY: "-100deg" }]
}
```
